### ISSUE TITLE
Time issue for .ass files

### ISSUE THREAD

**Issue by someonelike-u** [Ristellise/AegisubDC#16] opened 2021-02-22 18:54 UTC
Hello,

I noticed something wrong about how AegisubDC reads and formats the time for .ass files:
If a .srt file contains seconds with 3 digits after the comma, the seconds will not be rounded. So it's OK.
In case of a .ass file, the seconds will be rounded with 2 digits after the comma.

It is exactly the same issue like this one https://github.com/Ristellise/AegisubDC/issues/11
This patch https://github.com/Ristellise/AegisubDC/commit/52033509f199c68a3235da318f1fc391e5bda26e seems to fix the issue only for .srt file.

Is it possible to apply the same fix for .ass files?

Best regards.

**Comment by Ristellise** [comment] 2021-02-22 19:18
> Hello,
> 
> I noticed something wrong about how AegisubDC reads and formats the time for .ass files:
> If a .srt file contains seconds with 3 digits after the comma, the seconds will not be rounded. So it's OK.
> In case of a .ass file, the seconds will be rounded with 2 digits after the comma.
> 
> It is exactly the same issue like this one #11
> This patch [5203350](https://github.com/Ristellise/AegisubDC/commit/52033509f199c68a3235da318f1fc391e5bda26e) seems to fix the issue only for .srt file.
> 
> Is it possible to apply the same fix for .ass files?
> 
> Best regards.

Unlikely to be fixed as of now. I'll ask around if it's a decent idea or not.

**Comment by someonelike-u** [comment] 2021-02-22 19:38
OK, thank you for your response.
Honestly, I don't know if it is real issue.
I noticed this issue after patching this code https://github.com/isaacbernat/netflix-to-srt in order to generate .ass file directly.
But, latest TypesettingTools'releases seem no problem, even latest official releases like the 3.2.2 version...

**Comment by Ristellise** [comment] 2021-02-22 19:52
> in order to generate .ass file directly.
Did you leave in 3 millisecond precision? because in ASS format, that's non-standard.

**Comment by MadokaAyukawa** [comment] 2021-02-22 20:18
I thought .ass only kept time to 2 decimal places as the raw .ass file in Notepad++ only has 2 decimal places. The .srt fix was important as the TPP did not account for 3 decimal places so it would not fix tiny overlaps like 10.003 with the next line starting at 10.000. I've had multiple cases where the TPP would leave those overlaps, but the new DC seems to avoid that as it rounds those out.

**Comment by someonelike-u** [comment] 2021-02-22 20:52
> > in order to generate .ass file directly.
> 
> Did you leave in 3 millisecond precision? because in ASS format, that's non-standard.

Yes, I did. But now I am facing to the issue, I let until centisecond

**Comment by moi15moi** [comment] 2021-03-19 18:37
Hi,
I think that the problem is not resolve with the time.

[Example.zip](https://github.com/Ristellise/AegisubDC/files/6173373/Example.zip)
If you open the ass I have to you via this program, the time is good.
But, if you mux the subs and open it via mpv, the time is not the same (so, not good).

I created the .ass by opening the .srt and selecting the option _Save Subs ass..._

Also, I can see that the .srt is not properly time when I play the video on mpv, but I think that mpv does not properly manage .srt.

Thank you

**Comment by MadokaAyukawa** [comment] 2021-03-19 18:52
Yes, there seems to be some issue loading the .srt into AS. This is the raw .srt file loaded into NPP.

![image](https://user-images.githubusercontent.com/44476321/111828897-35e54300-88a9-11eb-9b85-c7346f27ef77.png)

But the same file in Aegisub 9212 looks like:

![image](https://user-images.githubusercontent.com/44476321/111828985-53b2a800-88a9-11eb-8008-865b7cc8fe64.png)

So it took 0.01 off.

**Comment by Ristellise** [comment] 2021-03-25 01:36
> Yes, there seems to be some issue loading the .srt into AS. This is the raw .srt file loaded into NPP.
> 
> ![image](https://user-images.githubusercontent.com/44476321/111828897-35e54300-88a9-11eb-9b85-c7346f27ef77.png)
> 
> But the same file in Aegisub 9212 looks like:
> 
> ![image](https://user-images.githubusercontent.com/44476321/111828985-53b2a800-88a9-11eb-8008-865b7cc8fe64.png)
> 
> So it took 0.01 off.
> 
> I then exported the File loaded into AS 9212 as a new .srt file and got this.
> 
> ![image](https://user-images.githubusercontent.com/44476321/111829489-ff5bf800-88a9-11eb-996b-3711bf53aef4.png)
> 
> Then loading this new .srt into AS resulted in:
> 
> ![image](https://user-images.githubusercontent.com/44476321/111829555-11d63180-88aa-11eb-8c2a-7f8dcb3b43ad.png)
> 
> I then edited this file, saved it, and reloaded it and got:
> 
> ![image](https://user-images.githubusercontent.com/44476321/111831816-1fd98180-88ad-11eb-997d-7089bdbde2f9.png)
> 
> So, I'm slowly taking 0.01 with each load iteration.

Yeah, that's definitely a bug. thanks for reporting!

**Comment by moi15moi** [comment] 2021-03-27 00:23
Thank you :)

**Closed** 2021-07-13 13:03 UTC
Labels: bug
