### ISSUE TITLE
Font rendering regression (9210 -> 9211)

### ISSUE THREAD

**Issue by CoffeeStraw** [Ristellise/AegisubDC#7] opened 2021-01-06 15:10 UTC
Hi,
I've recently discovered your builds, thank you for your work!

It seems like there is a regression in the libass used in 9211 release, as it does not render some fonts anymore, while in 9210 everything seems to work just fine. As an example, consider the [Migu 1P font](https://www.freejapanesefont.com/migu-font-%E3%83%9F%E3%82%B0%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88/), which you can freely download, but other fonts like Cambria Math or MS Gothic suffer from the same issue.

I'm also leaving some screens, thank you in advance!

9211
![image](https://user-images.githubusercontent.com/16942527/103783863-86365e00-5039-11eb-8f36-52e17c37ffb7.png)

9210
![image](https://user-images.githubusercontent.com/16942527/103783934-9fd7a580-5039-11eb-93d3-6c78f73d38d0.png)

**Comment by Ristellise** [comment] 2021-01-07 09:15
I'm soo tempted to write my own font loading library for windows...  
Anyway, this is likely due to how Aegisub overrides libass behavior for vsfilter compatibility. To be specific, the difference between GDI (Aegisub Override) vs DirectWrite (libass native).

I'll look into it but at this point, I kinda half gave up trying.

**Comment by CoffeeStraw** [comment] 2021-01-07 11:04
Kinda happy you fastly located the issue though!
Hope you can get that fixed, since I would be happy to use an updated version of Aegisub.

**Comment by petzku** [comment] 2021-01-07 18:56
This looks like the actual problem is Aegisub not finding the font in the first place. 9210 would fall back to Arial, whereas 9211 simply renders nothing.

All of the following screenshots are taken from 9211 (v2), using libass as a renderer. Note especially the `1` glyph—the font shown in the original issue is Arial, not Migu 1P.
![image](https://user-images.githubusercontent.com/5639335/103932437-81050c00-512a-11eb-9934-72a26ab727de.png)

![image](https://user-images.githubusercontent.com/5639335/103932461-87938380-512a-11eb-98d5-852238b59888.png)

![image](https://user-images.githubusercontent.com/5639335/103932560-b14caa80-512a-11eb-9e00-606fb9231a52.png)

**Comment by CoffeeStraw** [comment] 2021-01-07 19:07
Your explanation seems reasonable.
I've downloaded again 9211, but I'm not getting the same results you're getting (Migu 1P rendering). So they're not from 9211 right?

**Comment by CoffeeStraw** [comment] 2021-01-07 19:12
UPDATE:
Actually, it seems now to work with Migu 1P after re-installing the font (mystery), but I'm still having the same issue with Cambria Math and MS Gothic (as well as a lot of other fonts).

**Comment by petzku** [comment] 2021-01-07 19:19
I had some problems getting Migu 1P to work. FontBase would not detect it at all, but it worked after installing the font globally in Windows.

I can reproduce Cambria Math failing to render in 9211, though. Renders fine using `CSRI/vsfilter_textsub` in 9211, as well as using libass in 9210.

**Comment by petzku** [comment] 2021-01-07 19:23
Just thought to test with an old(ish) build of TypesettingTools/Aegisub (r8992). It has the same behaviour as 9211 (renders nothing for Cambria Math).

I guess a current workaround would be to use `CSRI/vsfilter_textsub` instead of libass when working with affected fonts.

**Comment by Ristellise** [comment] 2021-01-07 19:26
Cambria Math failing to render in 9211 might be due to GDI not detecting ttc files (or to that effect).

I might try fontconfig, seeing how there is a vcpkg package for it...

**Comment by CoffeeStraw** [comment] 2021-01-07 21:46
> I had some problems getting Migu 1P to work. FontBase would not detect it at all, but it worked after installing the font globally in Windows.

That must be what I've done unconsciously (since I've done it quickly)! It is still quite strange why does it happens... Could it be due to some recent Windows' update?

**Comment by Ristellise** [comment] 2021-01-09 01:27
> > I had some problems getting Migu 1P to work. FontBase would not detect it at all, but it worked after installing the font globally in Windows.
> 
> That must be what I've done unconsciously (since I've done it quickly)! It is still quite strange why does it happens... Could it be due to some recent Windows' update?

A windows update should not affect Aegisub (in general)

**Comment by IAmVisco** [comment] 2021-03-12 08:13
Not sure if the issue is related but I decided to post here instead of creating a new issue. After updating from 9210 to 9212 (also checked in 9211 v2, began there), my fonts stopped rendering correctly too. The font in question is [Jaldi](https://fonts.google.com/specimen/Jaldi?preview.text_type=custom), more specifically its Bold variant.

9210
![image](https://user-images.githubusercontent.com/18630605/110911303-90b7f100-8323-11eb-80c2-5d6d634797a9.png)

9211 v2
![image](https://user-images.githubusercontent.com/18630605/110911068-40409380-8323-11eb-9639-16dc89ad5444.png)

From my experiments, it's probably related to the fact that the library loads font weights incorrectly - if I use FFmpeg to burn in the subs, the resulting video has the correct font (although if I use PotPlayer and include the .ass file, the player also renders incorrect fonts). Funny enough, deleting Regular and leaving only Bold style for the font fixes issue in 9211 and 9212 (well, because there is nothing to render other than that one style).

**Comment by Ristellise** [comment] 2021-07-13 13:02
Should be resolved with Release 9213

**Closed by Ristellise** 2021-07-13 13:02 UTC
Labels: bug
